export interface Country {
  name: string;
  code: string;
  flag: string;
  timezone: string;
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", code: "AF", flag: "🇦🇫", timezone: "Asia/Kabul" },
  { name: "Albania", code: "AL", flag: "🇦🇱", timezone: "Europe/Tirane" },
  { name: "Algeria", code: "DZ", flag: "🇩🇿", timezone: "Africa/Algiers" },
  { name: "Andorra", code: "AD", flag: "🇦🇩", timezone: "Europe/Andorra" },
  { name: "Angola", code: "AO", flag: "🇦🇴", timezone: "Africa/Luanda" },
  { name: "Antigua and Barbuda", code: "AG", flag: "🇦🇬", timezone: "America/Antigua" },
  { name: "Argentina", code: "AR", flag: "🇦🇷", timezone: "America/Argentina/Buenos_Aires" },
  { name: "Armenia", code: "AM", flag: "🇦🇲", timezone: "Asia/Yerevan" },
  { name: "Australia", code: "AU", flag: "🇦🇺", timezone: "Australia/Sydney" },
  { name: "Austria", code: "AT", flag: "🇦🇹", timezone: "Europe/Vienna" },
  { name: "Azerbaijan", code: "AZ", flag: "🇦🇿", timezone: "Asia/Baku" },
  { name: "Bahamas", code: "BS", flag: "🇧🇸", timezone: "America/Nassau" },
  { name: "Bahrain", code: "BH", flag: "🇧🇭", timezone: "Asia/Bahrain" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩", timezone: "Asia/Dhaka" },
  { name: "Barbados", code: "BB", flag: "🇧🇧", timezone: "America/Barbados" },
  { name: "Belarus", code: "BY", flag: "🇧🇾", timezone: "Europe/Minsk" },
  { name: "Belgium", code: "BE", flag: "🇧🇪", timezone: "Europe/Brussels" },
  { name: "Belize", code: "BZ", flag: "🇧🇿", timezone: "America/Belize" },
  { name: "Benin", code: "BJ", flag: "🇧🇯", timezone: "Africa/Porto-Novo" },
  { name: "Bhutan", code: "BT", flag: "🇧🇹", timezone: "Asia/Thimphu" },
  { name: "Bolivia", code: "BO", flag: "🇧🇴", timezone: "America/La_Paz" },
  { name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦", timezone: "Europe/Sarajevo" },
  { name: "Botswana", code: "BW", flag: "🇧🇼", timezone: "Africa/Gaborone" },
  { name: "Brazil", code: "BR", flag: "🇧🇷", timezone: "America/Sao_Paulo" },
  { name: "Brunei", code: "BN", flag: "🇧🇳", timezone: "Asia/Brunei" },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬", timezone: "Europe/Sofia" },
  { name: "Burkina Faso", code: "BF", flag: "🇧🇫", timezone: "Africa/Ouagadougou" },
  { name: "Burundi", code: "BI", flag: "🇧🇮", timezone: "Africa/Bujumbura" },
  { name: "Cabo Verde", code: "CV", flag: "🇨🇻", timezone: "Atlantic/Cape_Verde" },
  { name: "Cambodia", code: "KH", flag: "🇰🇭", timezone: "Asia/Phnom_Penh" },
  { name: "Cameroon", code: "CM", flag: "🇨🇲", timezone: "Africa/Douala" },
  { name: "Canada", code: "CA", flag: "🇨🇦", timezone: "America/Toronto" },
  { name: "Central African Republic", code: "CF", flag: "🇨🇫", timezone: "Africa/Bangui" },
  { name: "Chad", code: "TD", flag: "🇹🇩", timezone: "Africa/Ndjamena" },
  { name: "Chile", code: "CL", flag: "🇨🇱", timezone: "America/Santiago" },
  { name: "China", code: "CN", flag: "🇨🇳", timezone: "Asia/Shanghai" },
  { name: "Colombia", code: "CO", flag: "🇨🇴", timezone: "America/Bogota" },
  { name: "Comoros", code: "KM", flag: "🇰🇲", timezone: "Indian/Comoro" },
  { name: "Congo", code: "CG", flag: "🇨🇬", timezone: "Africa/Brazzaville" },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷", timezone: "America/Costa_Rica" },
  { name: "Côte d'Ivoire", code: "CI", flag: "🇨🇮", timezone: "Africa/Abidjan" },
  { name: "Croatia", code: "HR", flag: "🇭🇷", timezone: "Europe/Zagreb" },
  { name: "Cuba", code: "CU", flag: "🇨🇺", timezone: "America/Havana" },
  { name: "Cyprus", code: "CY", flag: "🇨🇾", timezone: "Asia/Nicosia" },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿", timezone: "Europe/Prague" },
  { name: "Denmark", code: "DK", flag: "🇩🇰", timezone: "Europe/Copenhagen" },
  { name: "Djibouti", code: "DJ", flag: "🇩🇯", timezone: "Africa/Djibouti" },
  { name: "Dominica", code: "DM", flag: "🇩🇲", timezone: "America/Dominica" },
  { name: "Dominican Republic", code: "DO", flag: "🇩🇴", timezone: "America/Santo_Domingo" },
  { name: "DR Congo", code: "CD", flag: "🇨🇩", timezone: "Africa/Kinshasa" },
  { name: "Ecuador", code: "EC", flag: "🇪🇨", timezone: "America/Guayaquil" },
  { name: "Egypt", code: "EG", flag: "🇪🇬", timezone: "Africa/Cairo" },
  { name: "El Salvador", code: "SV", flag: "🇸🇻", timezone: "America/El_Salvador" },
  { name: "Equatorial Guinea", code: "GQ", flag: "🇬🇶", timezone: "Africa/Malabo" },
  { name: "Eritrea", code: "ER", flag: "🇪🇷", timezone: "Africa/Asmara" },
  { name: "Estonia", code: "EE", flag: "🇪🇪", timezone: "Europe/Tallinn" },
  { name: "Eswatini", code: "SZ", flag: "🇸🇿", timezone: "Africa/Mbabane" },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹", timezone: "Africa/Addis_Ababa" },
  { name: "Fiji", code: "FJ", flag: "🇫🇯", timezone: "Pacific/Fiji" },
  { name: "Finland", code: "FI", flag: "🇫🇮", timezone: "Europe/Helsinki" },
  { name: "France", code: "FR", flag: "🇫🇷", timezone: "Europe/Paris" },
  { name: "Gabon", code: "GA", flag: "🇬🇦", timezone: "Africa/Libreville" },
  { name: "Gambia", code: "GM", flag: "🇬🇲", timezone: "Africa/Banjul" },
  { name: "Georgia", code: "GE", flag: "🇬🇪", timezone: "Asia/Tbilisi" },
  { name: "Germany", code: "DE", flag: "🇩🇪", timezone: "Europe/Berlin" },
  { name: "Ghana", code: "GH", flag: "🇬🇭", timezone: "Africa/Accra" },
  { name: "Greece", code: "GR", flag: "🇬🇷", timezone: "Europe/Athens" },
  { name: "Grenada", code: "GD", flag: "🇬🇩", timezone: "America/Grenada" },
  { name: "Guatemala", code: "GT", flag: "🇬🇹", timezone: "America/Guatemala" },
  { name: "Guinea", code: "GN", flag: "🇬🇳", timezone: "Africa/Conakry" },
  { name: "Guinea-Bissau", code: "GW", flag: "🇬🇼", timezone: "Africa/Bissau" },
  { name: "Guyana", code: "GY", flag: "🇬🇾", timezone: "America/Guyana" },
  { name: "Haiti", code: "HT", flag: "🇭🇹", timezone: "America/Port-au-Prince" },
  { name: "Honduras", code: "HN", flag: "🇭🇳", timezone: "America/Tegucigalpa" },
  { name: "Hungary", code: "HU", flag: "🇭🇺", timezone: "Europe/Budapest" },
  { name: "Iceland", code: "IS", flag: "🇮🇸", timezone: "Atlantic/Reykjavik" },
  { name: "India", code: "IN", flag: "🇮🇳", timezone: "Asia/Kolkata" },
  { name: "Indonesia", code: "ID", flag: "🇮🇩", timezone: "Asia/Jakarta" },
  { name: "Iran", code: "IR", flag: "🇮🇷", timezone: "Asia/Tehran" },
  { name: "Iraq", code: "IQ", flag: "🇮🇶", timezone: "Asia/Baghdad" },
  { name: "Ireland", code: "IE", flag: "🇮🇪", timezone: "Europe/Dublin" },
  { name: "Israel", code: "IL", flag: "🇮🇱", timezone: "Asia/Jerusalem" },
  { name: "Italy", code: "IT", flag: "🇮🇹", timezone: "Europe/Rome" },
  { name: "Jamaica", code: "JM", flag: "🇯🇲", timezone: "America/Jamaica" },
  { name: "Japan", code: "JP", flag: "🇯🇵", timezone: "Asia/Tokyo" },
  { name: "Jordan", code: "JO", flag: "🇯🇴", timezone: "Asia/Amman" },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿", timezone: "Asia/Almaty" },
  { name: "Kenya", code: "KE", flag: "🇰🇪", timezone: "Africa/Nairobi" },
  { name: "Kiribati", code: "KI", flag: "🇰🇮", timezone: "Pacific/Tarawa" },
  { name: "Kuwait", code: "KW", flag: "🇰🇼", timezone: "Asia/Kuwait" },
  { name: "Kyrgyzstan", code: "KG", flag: "🇰🇬", timezone: "Asia/Bishkek" },
  { name: "Laos", code: "LA", flag: "🇱🇦", timezone: "Asia/Vientiane" },
  { name: "Latvia", code: "LV", flag: "🇱🇻", timezone: "Europe/Riga" },
  { name: "Lebanon", code: "LB", flag: "🇱🇧", timezone: "Asia/Beirut" },
  { name: "Lesotho", code: "LS", flag: "🇱🇸", timezone: "Africa/Maseru" },
  { name: "Liberia", code: "LR", flag: "🇱🇷", timezone: "Africa/Monrovia" },
  { name: "Libya", code: "LY", flag: "🇱🇾", timezone: "Africa/Tripoli" },
  { name: "Liechtenstein", code: "LI", flag: "🇱🇮", timezone: "Europe/Vaduz" },
  { name: "Lithuania", code: "LT", flag: "🇱🇹", timezone: "Europe/Vilnius" },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺", timezone: "Europe/Luxembourg" },
  { name: "Madagascar", code: "MG", flag: "🇲🇬", timezone: "Indian/Antananarivo" },
  { name: "Malawi", code: "MW", flag: "🇲🇼", timezone: "Africa/Blantyre" },
  { name: "Malaysia", code: "MY", flag: "🇲🇾", timezone: "Asia/Kuala_Lumpur" },
  { name: "Maldives", code: "MV", flag: "🇲🇻", timezone: "Indian/Maldives" },
  { name: "Mali", code: "ML", flag: "🇲🇱", timezone: "Africa/Bamako" },
  { name: "Malta", code: "MT", flag: "🇲🇹", timezone: "Europe/Malta" },
  { name: "Marshall Islands", code: "MH", flag: "🇲🇭", timezone: "Pacific/Majuro" },
  { name: "Mauritania", code: "MR", flag: "🇲🇷", timezone: "Africa/Nouakchott" },
  { name: "Mauritius", code: "MU", flag: "🇲🇺", timezone: "Indian/Mauritius" },
  { name: "Mexico", code: "MX", flag: "🇲🇽", timezone: "America/Mexico_City" },
  { name: "Micronesia", code: "FM", flag: "🇫🇲", timezone: "Pacific/Chuuk" },
  { name: "Moldova", code: "MD", flag: "🇲🇩", timezone: "Europe/Chisinau" },
  { name: "Monaco", code: "MC", flag: "🇲🇨", timezone: "Europe/Monaco" },
  { name: "Mongolia", code: "MN", flag: "🇲🇳", timezone: "Asia/Ulaanbaatar" },
  { name: "Montenegro", code: "ME", flag: "🇲🇪", timezone: "Europe/Podgorica" },
  { name: "Morocco", code: "MA", flag: "🇲🇦", timezone: "Africa/Casablanca" },
  { name: "Mozambique", code: "MZ", flag: "🇲🇿", timezone: "Africa/Maputo" },
  { name: "Myanmar", code: "MM", flag: "🇲🇲", timezone: "Asia/Yangon" },
  { name: "Namibia", code: "NA", flag: "🇳🇦", timezone: "Africa/Windhoek" },
  { name: "Nauru", code: "NR", flag: "🇳🇷", timezone: "Pacific/Nauru" },
  { name: "Nepal", code: "NP", flag: "🇳🇵", timezone: "Asia/Kathmandu" },
  { name: "Netherlands", code: "NL", flag: "🇳🇱", timezone: "Europe/Amsterdam" },
  { name: "New Zealand", code: "NZ", flag: "🇳🇿", timezone: "Pacific/Auckland" },
  { name: "Nicaragua", code: "NI", flag: "🇳🇮", timezone: "America/Managua" },
  { name: "Niger", code: "NE", flag: "🇳🇪", timezone: "Africa/Niamey" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬", timezone: "Africa/Lagos" },
  { name: "North Korea", code: "KP", flag: "🇰🇵", timezone: "Asia/Pyongyang" },
  { name: "North Macedonia", code: "MK", flag: "🇲🇰", timezone: "Europe/Skopje" },
  { name: "Norway", code: "NO", flag: "🇳🇴", timezone: "Europe/Oslo" },
  { name: "Oman", code: "OM", flag: "🇴🇲", timezone: "Asia/Muscat" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰", timezone: "Asia/Karachi" },
  { name: "Palau", code: "PW", flag: "🇵🇼", timezone: "Pacific/Palau" },
  { name: "Palestine", code: "PS", flag: "🇵🇸", timezone: "Asia/Gaza" },
  { name: "Panama", code: "PA", flag: "🇵🇦", timezone: "America/Panama" },
  { name: "Papua New Guinea", code: "PG", flag: "🇵🇬", timezone: "Pacific/Port_Moresby" },
  { name: "Paraguay", code: "PY", flag: "🇵🇾", timezone: "America/Asuncion" },
  { name: "Peru", code: "PE", flag: "🇵🇪", timezone: "America/Lima" },
  { name: "Philippines", code: "PH", flag: "🇵🇭", timezone: "Asia/Manila" },
  { name: "Poland", code: "PL", flag: "🇵🇱", timezone: "Europe/Warsaw" },
  { name: "Portugal", code: "PT", flag: "🇵🇹", timezone: "Europe/Lisbon" },
  { name: "Qatar", code: "QA", flag: "🇶🇦", timezone: "Asia/Qatar" },
  { name: "Romania", code: "RO", flag: "🇷🇴", timezone: "Europe/Bucharest" },
  { name: "Russia", code: "RU", flag: "🇷🇺", timezone: "Europe/Moscow" },
  { name: "Rwanda", code: "RW", flag: "🇷🇼", timezone: "Africa/Kigali" },
  { name: "Saint Kitts and Nevis", code: "KN", flag: "🇰🇳", timezone: "America/St_Kitts" },
  { name: "Saint Lucia", code: "LC", flag: "🇱🇨", timezone: "America/St_Lucia" },
  { name: "Saint Vincent and the Grenadines", code: "VC", flag: "🇻🇨", timezone: "America/St_Vincent" },
  { name: "Samoa", code: "WS", flag: "🇼🇸", timezone: "Pacific/Apia" },
  { name: "San Marino", code: "SM", flag: "🇸🇲", timezone: "Europe/San_Marino" },
  { name: "Sao Tome and Principe", code: "ST", flag: "🇸🇹", timezone: "Africa/Sao_Tome" },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦", timezone: "Asia/Riyadh" },
  { name: "Senegal", code: "SN", flag: "🇸🇳", timezone: "Africa/Dakar" },
  { name: "Serbia", code: "RS", flag: "🇷🇸", timezone: "Europe/Belgrade" },
  { name: "Seychelles", code: "SC", flag: "🇸🇨", timezone: "Indian/Mahe" },
  { name: "Sierra Leone", code: "SL", flag: "🇸🇱", timezone: "Africa/Freetown" },
  { name: "Singapore", code: "SG", flag: "🇸🇬", timezone: "Asia/Singapore" },
  { name: "Slovakia", code: "SK", flag: "🇸🇰", timezone: "Europe/Bratislava" },
  { name: "Slovenia", code: "SI", flag: "🇸🇮", timezone: "Europe/Ljubljana" },
  { name: "Solomon Islands", code: "SB", flag: "🇸🇧", timezone: "Pacific/Guadalcanal" },
  { name: "Somalia", code: "SO", flag: "🇸🇴", timezone: "Africa/Mogadishu" },
  { name: "South Africa", code: "ZA", flag: "🇿🇦", timezone: "Africa/Johannesburg" },
  { name: "South Korea", code: "KR", flag: "🇰🇷", timezone: "Asia/Seoul" },
  { name: "South Sudan", code: "SS", flag: "🇸🇸", timezone: "Africa/Juba" },
  { name: "Spain", code: "ES", flag: "🇪🇸", timezone: "Europe/Madrid" },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰", timezone: "Asia/Colombo" },
  { name: "Sudan", code: "SD", flag: "🇸🇩", timezone: "Africa/Khartoum" },
  { name: "Suriname", code: "SR", flag: "🇸🇷", timezone: "America/Paramaribo" },
  { name: "Sweden", code: "SE", flag: "🇸🇪", timezone: "Europe/Stockholm" },
  { name: "Switzerland", code: "CH", flag: "🇨🇭", timezone: "Europe/Zurich" },
  { name: "Syria", code: "SY", flag: "🇸🇾", timezone: "Asia/Damascus" },
  { name: "Taiwan", code: "TW", flag: "🇹🇼", timezone: "Asia/Taipei" },
  { name: "Tajikistan", code: "TJ", flag: "🇹🇯", timezone: "Asia/Dushanbe" },
  { name: "Tanzania", code: "TZ", flag: "🇹🇿", timezone: "Africa/Dar_es_Salaam" },
  { name: "Thailand", code: "TH", flag: "🇹🇭", timezone: "Asia/Bangkok" },
  { name: "Timor-Leste", code: "TL", flag: "🇹🇱", timezone: "Asia/Dili" },
  { name: "Togo", code: "TG", flag: "🇹🇬", timezone: "Africa/Lome" },
  { name: "Tonga", code: "TO", flag: "🇹🇴", timezone: "Pacific/Tongatapu" },
  { name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹", timezone: "America/Port_of_Spain" },
  { name: "Tunisia", code: "TN", flag: "🇹🇳", timezone: "Africa/Tunis" },
  { name: "Turkey", code: "TR", flag: "🇹🇷", timezone: "Europe/Istanbul" },
  { name: "Turkmenistan", code: "TM", flag: "🇹🇲", timezone: "Asia/Ashgabat" },
  { name: "Tuvalu", code: "TV", flag: "🇹🇻", timezone: "Pacific/Funafuti" },
  { name: "Uganda", code: "UG", flag: "🇺🇬", timezone: "Africa/Kampala" },
  { name: "Ukraine", code: "UA", flag: "🇺🇦", timezone: "Europe/Kyiv" },
  { name: "United Arab Emirates", code: "AE", flag: "🇦🇪", timezone: "Asia/Dubai" },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧", timezone: "Europe/London" },
  { name: "United States", code: "US", flag: "🇺🇸", timezone: "America/New_York" },
  { name: "Uruguay", code: "UY", flag: "🇺🇾", timezone: "America/Montevideo" },
  { name: "Uzbekistan", code: "UZ", flag: "🇺🇿", timezone: "Asia/Tashkent" },
  { name: "Vanuatu", code: "VU", flag: "🇻🇺", timezone: "Pacific/Efate" },
  { name: "Vatican City", code: "VA", flag: "🇻🇦", timezone: "Europe/Vatican" },
  { name: "Venezuela", code: "VE", flag: "🇻🇪", timezone: "America/Caracas" },
  { name: "Vietnam", code: "VN", flag: "🇻🇳", timezone: "Asia/Ho_Chi_Minh" },
  { name: "Yemen", code: "YE", flag: "🇾🇪", timezone: "Asia/Aden" },
  { name: "Zambia", code: "ZM", flag: "🇿🇲", timezone: "Africa/Lusaka" },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼", timezone: "Africa/Harare" },
];
