/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessClinicRouteImport } from './routes/wellness-clinic'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RelFiRouteImport } from './routes/rel-fi'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyChapterRouteImport } from './routes/my-chapter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CodeRouteImport } from './routes/code'
import { Route as AlphaMindsDailyRouteImport } from './routes/alpha-minds-daily'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LibraryRouteRouteImport } from './routes/library/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as HousesIndexRouteImport } from './routes/houses/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms/$roomId'
import { Route as RelFiTutorialRouteImport } from './routes/rel-fi/tutorial'
import { Route as RelFiAdminRouteImport } from './routes/rel-fi/admin'
import { Route as RegisterOnboardingRouteImport } from './routes/register/onboarding'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as PlansPlanIdRouteImport } from './routes/plans.$planId'
import { Route as LibraryArticleIdRouteImport } from './routes/library/$articleId'
import { Route as HousesHouseIdRouteImport } from './routes/houses/$houseId'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as ChallengesChallengeIdRouteImport } from './routes/challenges/$challengeId'
import { Route as RelFiBroadcastCodeRouteImport } from './routes/rel-fi/broadcast.$code'
import { Route as RoomsRoomIdPostsPostIdRouteImport } from './routes/rooms/$roomId.posts.$postId'

const WellnessClinicRoute = WellnessClinicRouteImport.update({
  id: '/wellness-clinic',
  path: '/wellness-clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RelFiRoute = RelFiRouteImport.update({
  id: '/rel-fi',
  path: '/rel-fi',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyChapterRoute = MyChapterRouteImport.update({
  id: '/my-chapter',
  path: '/my-chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphaMindsDailyRoute = AlphaMindsDailyRouteImport.update({
  id: '/alpha-minds-daily',
  path: '/alpha-minds-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRouteRoute = LibraryRouteRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRouteRoute,
} as any)
const HousesIndexRoute = HousesIndexRouteImport.update({
  id: '/houses/',
  path: '/houses/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RelFiTutorialRoute = RelFiTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => RelFiRoute,
} as any)
const RelFiAdminRoute = RelFiAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => RelFiRoute,
} as any)
const RegisterOnboardingRoute = RegisterOnboardingRouteImport.update({
  id: '/register/onboarding',
  path: '/register/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => PlansRoute,
} as any)
const LibraryArticleIdRoute = LibraryArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => LibraryRouteRoute,
} as any)
const HousesHouseIdRoute = HousesHouseIdRouteImport.update({
  id: '/houses/$houseId',
  path: '/houses/$houseId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesChallengeIdRoute = ChallengesChallengeIdRouteImport.update({
  id: '/challenges/$challengeId',
  path: '/challenges/$challengeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RelFiBroadcastCodeRoute = RelFiBroadcastCodeRouteImport.update({
  id: '/broadcast/$code',
  path: '/broadcast/$code',
  getParentRoute: () => RelFiRoute,
} as any)
const RoomsRoomIdPostsPostIdRoute = RoomsRoomIdPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/alpha-minds-daily': typeof AlphaMindsDailyRoute
  '/code': typeof CodeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/my-chapter': typeof MyChapterRoute
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRouteWithChildren
  '/rel-fi': typeof RelFiRouteWithChildren
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/wellness-clinic': typeof WellnessClinicRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/houses/$houseId': typeof HousesHouseIdRoute
  '/library/$articleId': typeof LibraryArticleIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/register/onboarding': typeof RegisterOnboardingRoute
  '/rel-fi/admin': typeof RelFiAdminRoute
  '/rel-fi/tutorial': typeof RelFiTutorialRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/challenges/': typeof ChallengesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/houses/': typeof HousesIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/rel-fi/broadcast/$code': typeof RelFiBroadcastCodeRoute
  '/rooms/$roomId/posts/$postId': typeof RoomsRoomIdPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alpha-minds-daily': typeof AlphaMindsDailyRoute
  '/code': typeof CodeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/my-chapter': typeof MyChapterRoute
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRouteWithChildren
  '/rel-fi': typeof RelFiRouteWithChildren
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/wellness-clinic': typeof WellnessClinicRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/houses/$houseId': typeof HousesHouseIdRoute
  '/library/$articleId': typeof LibraryArticleIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/register/onboarding': typeof RegisterOnboardingRoute
  '/rel-fi/admin': typeof RelFiAdminRoute
  '/rel-fi/tutorial': typeof RelFiTutorialRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/challenges': typeof ChallengesIndexRoute
  '/events': typeof EventsIndexRoute
  '/houses': typeof HousesIndexRoute
  '/library': typeof LibraryIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/register': typeof RegisterIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/rel-fi/broadcast/$code': typeof RelFiBroadcastCodeRoute
  '/rooms/$roomId/posts/$postId': typeof RoomsRoomIdPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/alpha-minds-daily': typeof AlphaMindsDailyRoute
  '/code': typeof CodeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/my-chapter': typeof MyChapterRoute
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRouteWithChildren
  '/rel-fi': typeof RelFiRouteWithChildren
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/wellness-clinic': typeof WellnessClinicRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/houses/$houseId': typeof HousesHouseIdRoute
  '/library/$articleId': typeof LibraryArticleIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/register/onboarding': typeof RegisterOnboardingRoute
  '/rel-fi/admin': typeof RelFiAdminRoute
  '/rel-fi/tutorial': typeof RelFiTutorialRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/challenges/': typeof ChallengesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/houses/': typeof HousesIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/rel-fi/broadcast/$code': typeof RelFiBroadcastCodeRoute
  '/rooms/$roomId/posts/$postId': typeof RoomsRoomIdPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/admin'
    | '/alpha-minds-daily'
    | '/code'
    | '/forgot-password'
    | '/journey'
    | '/login'
    | '/my-chapter'
    | '/notifications'
    | '/plans'
    | '/rel-fi'
    | '/settings'
    | '/subscription'
    | '/wellness-clinic'
    | '/challenges/$challengeId'
    | '/events/$eventId'
    | '/houses/$houseId'
    | '/library/$articleId'
    | '/plans/$planId'
    | '/profile/$username'
    | '/register/onboarding'
    | '/rel-fi/admin'
    | '/rel-fi/tutorial'
    | '/rooms/$roomId'
    | '/challenges/'
    | '/events/'
    | '/houses/'
    | '/library/'
    | '/profile/'
    | '/register/'
    | '/rooms/'
    | '/rel-fi/broadcast/$code'
    | '/rooms/$roomId/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alpha-minds-daily'
    | '/code'
    | '/forgot-password'
    | '/journey'
    | '/login'
    | '/my-chapter'
    | '/notifications'
    | '/plans'
    | '/rel-fi'
    | '/settings'
    | '/subscription'
    | '/wellness-clinic'
    | '/challenges/$challengeId'
    | '/events/$eventId'
    | '/houses/$houseId'
    | '/library/$articleId'
    | '/plans/$planId'
    | '/profile/$username'
    | '/register/onboarding'
    | '/rel-fi/admin'
    | '/rel-fi/tutorial'
    | '/rooms/$roomId'
    | '/challenges'
    | '/events'
    | '/houses'
    | '/library'
    | '/profile'
    | '/register'
    | '/rooms'
    | '/rel-fi/broadcast/$code'
    | '/rooms/$roomId/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/admin'
    | '/alpha-minds-daily'
    | '/code'
    | '/forgot-password'
    | '/journey'
    | '/login'
    | '/my-chapter'
    | '/notifications'
    | '/plans'
    | '/rel-fi'
    | '/settings'
    | '/subscription'
    | '/wellness-clinic'
    | '/challenges/$challengeId'
    | '/events/$eventId'
    | '/houses/$houseId'
    | '/library/$articleId'
    | '/plans/$planId'
    | '/profile/$username'
    | '/register/onboarding'
    | '/rel-fi/admin'
    | '/rel-fi/tutorial'
    | '/rooms/$roomId'
    | '/challenges/'
    | '/events/'
    | '/houses/'
    | '/library/'
    | '/profile/'
    | '/register/'
    | '/rooms/'
    | '/rel-fi/broadcast/$code'
    | '/rooms/$roomId/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRouteRoute: typeof LibraryRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AlphaMindsDailyRoute: typeof AlphaMindsDailyRoute
  CodeRoute: typeof CodeRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JourneyRoute: typeof JourneyRoute
  LoginRoute: typeof LoginRoute
  MyChapterRoute: typeof MyChapterRoute
  NotificationsRoute: typeof NotificationsRoute
  PlansRoute: typeof PlansRouteWithChildren
  RelFiRoute: typeof RelFiRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SubscriptionRoute: typeof SubscriptionRoute
  WellnessClinicRoute: typeof WellnessClinicRoute
  ChallengesChallengeIdRoute: typeof ChallengesChallengeIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  HousesHouseIdRoute: typeof HousesHouseIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  RegisterOnboardingRoute: typeof RegisterOnboardingRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRouteWithChildren
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  HousesIndexRoute: typeof HousesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness-clinic': {
      id: '/wellness-clinic'
      path: '/wellness-clinic'
      fullPath: '/wellness-clinic'
      preLoaderRoute: typeof WellnessClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rel-fi': {
      id: '/rel-fi'
      path: '/rel-fi'
      fullPath: '/rel-fi'
      preLoaderRoute: typeof RelFiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-chapter': {
      id: '/my-chapter'
      path: '/my-chapter'
      fullPath: '/my-chapter'
      preLoaderRoute: typeof MyChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alpha-minds-daily': {
      id: '/alpha-minds-daily'
      path: '/alpha-minds-daily'
      fullPath: '/alpha-minds-daily'
      preLoaderRoute: typeof AlphaMindsDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
    '/houses/': {
      id: '/houses/'
      path: '/houses'
      fullPath: '/houses/'
      preLoaderRoute: typeof HousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rel-fi/tutorial': {
      id: '/rel-fi/tutorial'
      path: '/tutorial'
      fullPath: '/rel-fi/tutorial'
      preLoaderRoute: typeof RelFiTutorialRouteImport
      parentRoute: typeof RelFiRoute
    }
    '/rel-fi/admin': {
      id: '/rel-fi/admin'
      path: '/admin'
      fullPath: '/rel-fi/admin'
      preLoaderRoute: typeof RelFiAdminRouteImport
      parentRoute: typeof RelFiRoute
    }
    '/register/onboarding': {
      id: '/register/onboarding'
      path: '/register/onboarding'
      fullPath: '/register/onboarding'
      preLoaderRoute: typeof RegisterOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof PlansRoute
    }
    '/library/$articleId': {
      id: '/library/$articleId'
      path: '/$articleId'
      fullPath: '/library/$articleId'
      preLoaderRoute: typeof LibraryArticleIdRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
    '/houses/$houseId': {
      id: '/houses/$houseId'
      path: '/houses/$houseId'
      fullPath: '/houses/$houseId'
      preLoaderRoute: typeof HousesHouseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$challengeId': {
      id: '/challenges/$challengeId'
      path: '/challenges/$challengeId'
      fullPath: '/challenges/$challengeId'
      preLoaderRoute: typeof ChallengesChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rel-fi/broadcast/$code': {
      id: '/rel-fi/broadcast/$code'
      path: '/broadcast/$code'
      fullPath: '/rel-fi/broadcast/$code'
      preLoaderRoute: typeof RelFiBroadcastCodeRouteImport
      parentRoute: typeof RelFiRoute
    }
    '/rooms/$roomId/posts/$postId': {
      id: '/rooms/$roomId/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/rooms/$roomId/posts/$postId'
      preLoaderRoute: typeof RoomsRoomIdPostsPostIdRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
  }
}

interface LibraryRouteRouteChildren {
  LibraryArticleIdRoute: typeof LibraryArticleIdRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteRouteChildren: LibraryRouteRouteChildren = {
  LibraryArticleIdRoute: LibraryArticleIdRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteRouteWithChildren = LibraryRouteRoute._addFileChildren(
  LibraryRouteRouteChildren,
)

interface PlansRouteChildren {
  PlansPlanIdRoute: typeof PlansPlanIdRoute
}

const PlansRouteChildren: PlansRouteChildren = {
  PlansPlanIdRoute: PlansPlanIdRoute,
}

const PlansRouteWithChildren = PlansRoute._addFileChildren(PlansRouteChildren)

interface RelFiRouteChildren {
  RelFiAdminRoute: typeof RelFiAdminRoute
  RelFiTutorialRoute: typeof RelFiTutorialRoute
  RelFiBroadcastCodeRoute: typeof RelFiBroadcastCodeRoute
}

const RelFiRouteChildren: RelFiRouteChildren = {
  RelFiAdminRoute: RelFiAdminRoute,
  RelFiTutorialRoute: RelFiTutorialRoute,
  RelFiBroadcastCodeRoute: RelFiBroadcastCodeRoute,
}

const RelFiRouteWithChildren = RelFiRoute._addFileChildren(RelFiRouteChildren)

interface RoomsRoomIdRouteChildren {
  RoomsRoomIdPostsPostIdRoute: typeof RoomsRoomIdPostsPostIdRoute
}

const RoomsRoomIdRouteChildren: RoomsRoomIdRouteChildren = {
  RoomsRoomIdPostsPostIdRoute: RoomsRoomIdPostsPostIdRoute,
}

const RoomsRoomIdRouteWithChildren = RoomsRoomIdRoute._addFileChildren(
  RoomsRoomIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRouteRoute: LibraryRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AlphaMindsDailyRoute: AlphaMindsDailyRoute,
  CodeRoute: CodeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JourneyRoute: JourneyRoute,
  LoginRoute: LoginRoute,
  MyChapterRoute: MyChapterRoute,
  NotificationsRoute: NotificationsRoute,
  PlansRoute: PlansRouteWithChildren,
  RelFiRoute: RelFiRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SubscriptionRoute: SubscriptionRoute,
  WellnessClinicRoute: WellnessClinicRoute,
  ChallengesChallengeIdRoute: ChallengesChallengeIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  HousesHouseIdRoute: HousesHouseIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  RegisterOnboardingRoute: RegisterOnboardingRoute,
  RoomsRoomIdRoute: RoomsRoomIdRouteWithChildren,
  ChallengesIndexRoute: ChallengesIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  HousesIndexRoute: HousesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
