/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as HousesIndexRouteImport } from './routes/houses/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms/$roomId'
import { Route as RegisterOnboardingRouteImport } from './routes/register/onboarding'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as HousesHouseIdRouteImport } from './routes/houses/$houseId'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as ChallengesChallengeIdRouteImport } from './routes/challenges/$challengeId'
import { Route as RoomsRoomIdPostsPostIdRouteImport } from './routes/rooms/$roomId.posts.$postId'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIndexRoute = HousesIndexRouteImport.update({
  id: '/houses/',
  path: '/houses/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterOnboardingRoute = RegisterOnboardingRouteImport.update({
  id: '/register/onboarding',
  path: '/register/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesHouseIdRoute = HousesHouseIdRouteImport.update({
  id: '/houses/$houseId',
  path: '/houses/$houseId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesChallengeIdRoute = ChallengesChallengeIdRouteImport.update({
  id: '/challenges/$challengeId',
  path: '/challenges/$challengeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdPostsPostIdRoute = RoomsRoomIdPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/houses/$houseId': typeof HousesHouseIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/register/onboarding': typeof RegisterOnboardingRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/challenges/': typeof ChallengesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/houses/': typeof HousesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/rooms/$roomId/posts/$postId': typeof RoomsRoomIdPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/houses/$houseId': typeof HousesHouseIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/register/onboarding': typeof RegisterOnboardingRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/challenges': typeof ChallengesIndexRoute
  '/events': typeof EventsIndexRoute
  '/houses': typeof HousesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/register': typeof RegisterIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/rooms/$roomId/posts/$postId': typeof RoomsRoomIdPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/houses/$houseId': typeof HousesHouseIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/register/onboarding': typeof RegisterOnboardingRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/challenges/': typeof ChallengesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/houses/': typeof HousesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/rooms/$roomId/posts/$postId': typeof RoomsRoomIdPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/subscription'
    | '/challenges/$challengeId'
    | '/events/$eventId'
    | '/houses/$houseId'
    | '/profile/$username'
    | '/register/onboarding'
    | '/rooms/$roomId'
    | '/challenges/'
    | '/events/'
    | '/houses/'
    | '/profile/'
    | '/register/'
    | '/rooms/'
    | '/rooms/$roomId/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/subscription'
    | '/challenges/$challengeId'
    | '/events/$eventId'
    | '/houses/$houseId'
    | '/profile/$username'
    | '/register/onboarding'
    | '/rooms/$roomId'
    | '/challenges'
    | '/events'
    | '/houses'
    | '/profile'
    | '/register'
    | '/rooms'
    | '/rooms/$roomId/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/subscription'
    | '/challenges/$challengeId'
    | '/events/$eventId'
    | '/houses/$houseId'
    | '/profile/$username'
    | '/register/onboarding'
    | '/rooms/$roomId'
    | '/challenges/'
    | '/events/'
    | '/houses/'
    | '/profile/'
    | '/register/'
    | '/rooms/'
    | '/rooms/$roomId/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionRoute: typeof SubscriptionRoute
  ChallengesChallengeIdRoute: typeof ChallengesChallengeIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  HousesHouseIdRoute: typeof HousesHouseIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  RegisterOnboardingRoute: typeof RegisterOnboardingRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRouteWithChildren
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  HousesIndexRoute: typeof HousesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/': {
      id: '/houses/'
      path: '/houses'
      fullPath: '/houses/'
      preLoaderRoute: typeof HousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/onboarding': {
      id: '/register/onboarding'
      path: '/register/onboarding'
      fullPath: '/register/onboarding'
      preLoaderRoute: typeof RegisterOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/$houseId': {
      id: '/houses/$houseId'
      path: '/houses/$houseId'
      fullPath: '/houses/$houseId'
      preLoaderRoute: typeof HousesHouseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$challengeId': {
      id: '/challenges/$challengeId'
      path: '/challenges/$challengeId'
      fullPath: '/challenges/$challengeId'
      preLoaderRoute: typeof ChallengesChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/posts/$postId': {
      id: '/rooms/$roomId/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/rooms/$roomId/posts/$postId'
      preLoaderRoute: typeof RoomsRoomIdPostsPostIdRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
  }
}

interface RoomsRoomIdRouteChildren {
  RoomsRoomIdPostsPostIdRoute: typeof RoomsRoomIdPostsPostIdRoute
}

const RoomsRoomIdRouteChildren: RoomsRoomIdRouteChildren = {
  RoomsRoomIdPostsPostIdRoute: RoomsRoomIdPostsPostIdRoute,
}

const RoomsRoomIdRouteWithChildren = RoomsRoomIdRoute._addFileChildren(
  RoomsRoomIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionRoute: SubscriptionRoute,
  ChallengesChallengeIdRoute: ChallengesChallengeIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  HousesHouseIdRoute: HousesHouseIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  RegisterOnboardingRoute: RegisterOnboardingRoute,
  RoomsRoomIdRoute: RoomsRoomIdRouteWithChildren,
  ChallengesIndexRoute: ChallengesIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  HousesIndexRoute: HousesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
